//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OperationDBEntities : DbContext
    {
        public OperationDBEntities()
            : base("name=OperationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Budget> Budget { get; set; }
    
        public virtual ObjectResult<spBudgetFilterByName_Result> spBudgetFilterByName(string nameOfOperation, string notes)
        {
            var nameOfOperationParameter = nameOfOperation != null ?
                new ObjectParameter("NameOfOperation", nameOfOperation) :
                new ObjectParameter("NameOfOperation", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("Notes", notes) :
                new ObjectParameter("Notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBudgetFilterByName_Result>("spBudgetFilterByName", nameOfOperationParameter, notesParameter);
        }
    }
}
