//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOfOperations
    {
        public int Id { get; set; }
        public string NameOfOperation { get; set; }
        public decimal ValueToChange { get; set; }
        public decimal AmountOfUserMoney { get; set; }
        public string Notes { get; set; }
    }
}
